### PR TITLE
Implement retry and multithreading

### PR DESCRIPTION
**Pull request by sumandari**
This patch is to implement retry-mechanism in request calls and use multithreading in multipart upload.

### CODE REVIEW

**Comment by sumandari** [comment]
@FredHaa please review it when you get a chance. Thanks!

**Comment by sumandari** [comment]
need to update unit test after push new changes

**Review by FredHaa — APPROVED** [review]
LGTM

**Comment by FredHaa** [comment]
Branch is forked from main?

**Comment by sumandari** [comment]
yes, from main branch. commit 8038b8b452696c804c8ef2c5dc85b6a83a858f9b
> Branch is forked from main?

**Comment by sumandari** [comment]
I'm converting this PR to draft and refactoring the read file process

**Review by FredHaa — APPROVED** [review]

**Pull request merged**
